name: CI

on:
  create:
  pull_request:
  push:
    branches:
      - main
      - automate

jobs:
  build:
    name: Test Publish
    runs-on: [ ubuntu-latest ]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      # Setup nanoc
      - name: Setup nanoc
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: make bundle
      - name: Build static site
        run: make build
      - name: Build swagger
        run: make swagger

  deploy:
    name: Build and deploy
    needs: build
    if: github.event_name == 'push'
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
      
